### ISSUE TITLE
pings disappear when interacting with chance shrine

### ISSUE THREAD

**Issue by Linzolle** [Kyryh/PermaPings#3]
if you try to put a perma ping on a chance shrine and then interact with it, the ping will disappear even if the chance shrine hasn't been emptied, and then you have to ping it twice to put the ping back on it. (implying that the ping is like, invisible since you have to press the button twice to unping and then reping it)

**Comment by Kyryh** [comment]
Fixed with 95539b5, though I don't have time to release it yet so feel free to clone the repo and build the mod in the meantime

**Comment by Linzolle** [comment]
I did go and try to build from source, however the issue persists specifically with chance shrines
